---
meraki: include('meraki')
defaults: any(required=False)
---
meraki:
  domains: list(include('domains'), required=False)
  template: include('template', required=False)
domains:
  name: str(min=1, max=128)
  url: str(min=1, max=255, required=False)
  administrator: include('administrator', required=False)
  organizations: list(include('organizations'))
template:
  networks: list(include('networks'), required=False)
administrator:
  name: str(min=1, max=128)
organizations:
  name: str(min=1, max=10, required=False)
  managed: bool(required=False)
  organization_id: int(required=False)
  login_security: include('login_security', required=False)
  snmp: include('snmp', required=False)
  appliance: include('appliance', required=False)
  networks: list(include('networks'),required=False)
login_security:
  enforce_password_expiration: bool(required=False)
  password_expiration_days: int(required=False)
  enforce_different_passwords: bool(required=False)
  num_different_passwords: int(required=False)
  enforce_strong_passwords: bool(required=False)
  enforce_account_lockout: bool(required=False)
  account_lockout_attempts: int(required=False)
  enforce_idle_timeout: bool(required=False)
  idle_timeout_minutes: int(required=False)
  enforce_two_factor_auth: bool(required=False)
  enforce_login_ip_ranges: bool(required=False)
  login_ip_ranges: list(str(), required=False)
  api_authentication: include('api_authentication', required=False)
api_authentication:
  enabled: bool(required=False)
  ranges: list(str(), required=False)
snmp:
  v2c: bool(required=False)
  v3: bool(required=False)
  v3_auth_mode: enum('SHA', 'MD5', required=False)
  v3_auth_pass: str(required=False)
  v3_priv_mode: enum('AES128', 'DES', required=False)
  v3_priv_pass: str(required=False)
  peer_ips: list(str(), required=False)
appliance:
  vpn_firewall_rules: include('vpn_firewall_rules', required=False)
vpn_firewall_rules:
  rules: list(include('vpn_firewall_rule'), required=False)
  syslog_default_rule: bool(required=False)
vpn_firewall_rule:
  comment: str(required=False)
  policy: enum('allow', 'deny', required=False)
  protocol: str(required=False)
  source_port: str(required=False)
  source_cidr: str(required=False)
  destination_port: str(required=False)
  destination_cidr: str(required=False)
  syslog: bool(required=False)
networks:
  name: str(min=1, max=127)
  time_zone: str(min=1, max=127, required=False)
  tags: list(str(min=1, max=255, required=False), required=False)
